import {defineType, defineField} from 'sanity'

export const openingHourSchema = defineType({
  name: 'openingHour',
  title: 'Opening Hours',
  type: 'object',
  fields: [
    defineField({
      name: 'day',
      title: 'Día de la Semana',
      type: 'string',
      options: {
        list: [
          {title: 'Lunes', value: 'Monday'},
          {title: 'Martes', value: 'Tuesday'},
          {title: 'Miércoles', value: 'Wednesday'},
          {title: 'Jueves', value: 'Thursday'},
          {title: 'Viernes', value: 'Friday'},
          {title: 'Sábado', value: 'Saturday'},
          {title: 'Domingo', value: 'Sunday'},
        ],
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'openingTime',
      title: 'Hora de Apertura',
      type: 'string',
      options: {
        list: [
          {title: '1:00', value: '1:00'},
          {title: '1:30', value: '1:30'},
          {title: '2:00', value: '2:00'},
          {title: '2:30', value: '2:30'},
          {title: '3:00', value: '3:00'},
          {title: '3:30', value: '3:30'},
          {title: '4:00', value: '4:00'},
          {title: '4:30', value: '4:30'},
          {title: '5:00', value: '5:00'},
          {title: '5:30', value: '5:30'},
          {title: '6:00', value: '6:00'},
          {title: '6:30', value: '6:30'},
          {title: '7:00', value: '7:00'},
          {title: '7:30', value: '7:30'},
          {title: '8:00', value: '8:00'},
          {title: '8:30', value: '8:30'},
          {title: '9:00', value: '9:00'},
          {title: '9:30', value: '9:30'},
          {title: '10:00', value: '10:00'},
          {title: '10:30', value: '10:30'},
          {title: '11:00', value: '11:00'},
          {title: '11:30', value: '11:30'},
          {title: '12:00', value: '12:00'},
          {title: '12:30', value: '12:30'},
        ],
      },
    }),
    defineField({
      name: 'openingTimeMeridiem',
      title: 'AM/PM Apertura',
      type: 'string',
      options: {
        list: [
          {title: 'AM', value: 'AM'},
          {title: 'PM', value: 'PM'},
        ],
      },
    }),
    defineField({
      name: 'closingTime',
      title: 'Hora de Cierre',
      type: 'string',
      options: {
        list: [
          {title: '1:00', value: '1:00'},
          {title: '1:30', value: '1:30'},
          {title: '2:00', value: '2:00'},
          {title: '2:30', value: '2:30'},
          {title: '3:00', value: '3:00'},
          {title: '3:30', value: '3:30'},
          {title: '4:00', value: '4:00'},
          {title: '4:30', value: '4:30'},
          {title: '5:00', value: '5:00'},
          {title: '5:30', value: '5:30'},
          {title: '6:00', value: '6:00'},
          {title: '6:30', value: '6:30'},
          {title: '7:00', value: '7:00'},
          {title: '7:30', value: '7:30'},
          {title: '8:00', value: '8:00'},
          {title: '8:30', value: '8:30'},
          {title: '9:00', value: '9:00'},
          {title: '9:30', value: '9:30'},
          {title: '10:00', value: '10:00'},
          {title: '10:30', value: '10:30'},
          {title: '11:00', value: '11:00'},
          {title: '11:30', value: '11:30'},
          {title: '12:00', value: '12:00'},
          {title: '12:30', value: '12:30'},
        ],
      },
    }),
    defineField({
      name: 'closingTimeMeridiem',
      title: 'AM/PM Cierre',
      type: 'string',
      options: {
        list: [
          {title: 'AM', value: 'AM'},
          {title: 'PM', value: 'PM'},
        ],
      },
    }),
    defineField({
      name: 'isClosed',
      title: 'Cerrado este día',
      type: 'boolean',
    }),
  ],
})
