import type { Restaurant } from "./types";

// Mock restaurant data with additional filter properties
export const mockRestaurants: Restaurant[] = [
  {
    name: "La Trattoria Italiana",
    location: {
      city: "Bogotá",
      neighborhood: "Chapinero",
      zone: {
        name: "Chapinero Alto",
        subzones: ["Chapinero Central", "Chapinero Alto"],
      },
    },
    distance: "A 2.5 kilómetros de ti",
    cuisine: "Italiana",
    priceRange: "$$",
    rating: 4.86,
    popularDish: "Pasta Carbonara",
    imageUrl:
      "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=800&auto=format&fit=crop&q=60",
    favorite: false,
    dietaryRestrictions: ["gluten-free", "vegetarian"],
    greatFor: ["romantic", "anniversaries"],
    features: ["reservations", "outdoor-seating"],
    establishmentType: ["restaurant", "bistro"],
    mealType: ["dinner", "lunch"],
  },
  {
    name: "El Taquito Mexicano",
    location: {
      city: "Medellín",
      neighborhood: "El Poblado",
      zone: {
        name: "Zona Rosa",
        subzones: ["Parque Lleras", "Calle 10"],
      },
    },
    distance: "A 1.8 kilómetros de ti",
    cuisine: "Mexicana",
    priceRange: "$",
    rating: 4.99,
    popularDish: "Tacos al Pastor",
    imageUrl:
      "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&auto=format&fit=crop&q=60",
    favorite: true,
    dietaryRestrictions: ["vegan"],
    greatFor: ["groups", "family"],
    features: ["pet-friendly", "takeout"],
    establishmentType: ["restaurant"],
    mealType: ["lunch", "dinner"],
  },
  {
    name: "Sushi Kawa",
    location: {
      city: "Cartagena",
      neighborhood: "Bocagrande",
      zone: {
        name: "Zona Hotelera",
        subzones: ["Bocagrande", "Castillogrande"],
      },
    },
    distance: "A 3.2 kilómetros de ti",
    cuisine: "Japonesa",
    priceRange: "$$$",
    rating: 4.85,
    popularDish: "Sushi Variado",
    imageUrl:
      "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800&auto=format&fit=crop&q=60",
    favorite: false,
    dietaryRestrictions: ["gluten-free"],
    greatFor: ["business", "romantic"],
    features: ["reservations", "wifi"],
    establishmentType: ["restaurant"],
    mealType: ["dinner"],
  },
  {
    name: "Verde Orgánico",
    location: {
      city: "Cali",
      neighborhood: "San Fernando",
      zone: {
        name: "Zona Norte",
        subzones: ["San Fernando", "Ciudad Jardín"],
      },
    },
    distance: "A 0.8 kilómetros de ti",
    cuisine: "Vegetariana",
    priceRange: "$$",
    rating: 4.85,
    popularDish: "Bowl de Quinoa",
    imageUrl:
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&auto=format&fit=crop&q=60",
    favorite: true,
    dietaryRestrictions: ["vegan", "gluten-free", "organic"],
    greatFor: ["solo-dining", "family"],
    features: ["wifi", "pet-friendly"],
    establishmentType: ["cafe", "restaurant"],
    mealType: ["breakfast", "lunch"],
  },
  {
    name: "Burger House",
    location: {
      city: "Barranquilla",
      neighborhood: "El Prado",
      zone: {
        name: "Zona Norte",
        subzones: ["El Prado", "Alto Prado"],
      },
    },
    distance: "A 1.5 kilómetros de ti",
    cuisine: "Comida Rápida",
    priceRange: "$",
    rating: 4.89,
    popularDish: "Hamburguesa Especial",
    imageUrl:
      "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=60",
    favorite: true,
    dietaryRestrictions: [],
    greatFor: ["family", "groups"],
    features: ["takeout", "delivery"],
    establishmentType: ["restaurant", "food-truck"],
    mealType: ["lunch", "dinner", "late-night"],
  },
  {
    name: "Gourmet Fusion",
    location: {
      city: "Pereira",
      neighborhood: "Centro",
      zone: {
        name: "Centro Histórico",
        subzones: ["Plaza de Bolívar", "Centro Comercial"],
      },
    },
    distance: "A 2.1 kilómetros de ti",
    cuisine: "Alta Cocina",
    priceRange: "$$$$",
    rating: 4.92,
    popularDish: "Risotto de Mariscos",
    imageUrl:
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&auto=format&fit=crop&q=60",
    favorite: true,
    dietaryRestrictions: ["halal", "kosher"],
    greatFor: ["anniversaries", "business", "romantic"],
    features: ["reservations", "parking"],
    establishmentType: ["restaurant", "rooftop"],
    mealType: ["dinner"],
  },
  {
    name: "Café del Parque",
    location: {
      city: "Bucaramanga",
      neighborhood: "Cabecera",
      zone: {
        name: "Zona Norte",
        subzones: ["Cabecera del Llano", "Centro Comercial"],
      },
    },
    distance: "A 0.5 kilómetros de ti",
    cuisine: "Café",
    priceRange: "$",
    rating: 5.0,
    popularDish: "Café Especial",
    imageUrl:
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&auto=format&fit=crop&q=60",
    favorite: false,
    dietaryRestrictions: ["vegetarian"],
    greatFor: ["solo-dining"],
    features: ["wifi", "outdoor-seating"],
    establishmentType: ["cafe", "bakery"],
    mealType: ["breakfast", "brunch", "coffee"],
  },
  {
    name: "La Cervecería",
    location: {
      city: "Santa Marta",
      neighborhood: "Rodadero",
      zone: {
        name: "Zona Turística",
        subzones: ["El Rodadero", "Bello Horizonte"],
      },
    },
    distance: "A 1.2 kilómetros de ti",
    cuisine: "Bar",
    priceRange: "$$",
    rating: 4.88,
    popularDish: "Tabla de Cervezas",
    imageUrl:
      "https://images.unsplash.com/photo-1516594915697-87eb3b1c14ea?w=800&auto=format&fit=crop&q=60",
    favorite: false,
    dietaryRestrictions: [],
    greatFor: ["groups", "view"],
    features: ["live-music", "outdoor-seating"],
    establishmentType: ["bar", "pub"],
    mealType: ["dinner", "drinks", "late-night"],
  },
  {
    name: "Dulce Tentación",
    location: {
      city: "Bogotá",
      neighborhood: "Usaquén",
      zone: {
        name: "Usaquén",
        subzones: ["Centro Comercial", "Parque"],
      },
    },
    distance: "A 1.7 kilómetros de ti",
    cuisine: "Postres",
    priceRange: "$$",
    rating: 4.95,
    popularDish: "Cheesecake de Frutos Rojos",
    imageUrl:
      "https://images.unsplash.com/photo-1534620808146-d33bb39128c2?w=800&auto=format&fit=crop&q=60",
    favorite: false,
    dietaryRestrictions: ["vegetarian"],
    greatFor: ["family", "romantic"],
    features: ["takeout", "wifi"],
    establishmentType: ["cafe", "bakery"],
    mealType: ["dessert", "coffee"],
  },
  {
    name: "Sabor Criollo",
    location: {
      city: "Medellín",
      neighborhood: "Laureles",
      zone: {
        name: "Laureles",
        subzones: ["Laureles", "Estadio"],
      },
    },
    distance: "A 2.3 kilómetros de ti",
    cuisine: "Colombiana",
    priceRange: "$$",
    rating: 4.82,
    popularDish: "Bandeja Paisa",
    imageUrl:
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&auto=format&fit=crop&q=60",
    favorite: false,
    dietaryRestrictions: [],
    greatFor: ["family", "groups"],
    features: ["parking", "wheelchair"],
    establishmentType: ["restaurant"],
    mealType: ["lunch", "dinner"],
  },
  {
    name: "Pizzería Napoli",
    location: {
      city: "Cali",
      neighborhood: "Granada",
      zone: {
        name: "Zona Rosa",
        subzones: ["Granada", "San Fernando"],
      },
    },
    distance: "A 1.9 kilómetros de ti",
    cuisine: "Italiana",
    priceRange: "$$",
    rating: 4.78,
    popularDish: "Pizza Margherita",
    imageUrl:
      "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=60",
    favorite: false,
    dietaryRestrictions: ["vegetarian"],
    greatFor: ["family", "groups"],
    features: ["delivery", "takeout"],
    establishmentType: ["restaurant"],
    mealType: ["lunch", "dinner"],
  },
  {
    name: "El Sazón Peruano",
    location: {
      city: "Bogotá",
      neighborhood: "Zona G",
      zone: {
        name: "Zona G",
        subzones: ["Zona G", "Chapinero"],
      },
    },
    distance: "A 3.0 kilómetros de ti",
    cuisine: "Peruana",
    priceRange: "$$$",
    rating: 4.91,
    popularDish: "Ceviche Mixto",
    imageUrl:
      "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=800&auto=format&fit=crop&q=60",
    favorite: true,
    dietaryRestrictions: ["gluten-free"],
    greatFor: ["business", "romantic"],
    features: ["reservations", "parking"],
    establishmentType: ["restaurant"],
    mealType: ["lunch", "dinner"],
  },
];

// Mock locations
export const mockLocations: string[] = [
  "Bogotá, Colombia",
  "Medellín, Colombia",
  "Cali, Colombia",
  "Barranquilla, Colombia",
  "Cartagena, Colombia",
  "Pereira, Colombia",
  "Bucaramanga, Colombia",
  "Santa Marta, Colombia",
  "Manizales, Colombia",
  "Pasto, Colombia",
];

// Mock cuisines
export const mockCuisines: string[] = [
  "Italiana",
  "Mexicana",
  "Japonesa",
  "Vegetariana",
  "Comida Rápida",
  "Alta Cocina",
  "Café",
  "Bar",
  "Postres",
  "Colombiana",
  "Peruana",
  "China",
  "Tailandesa",
  "India",
  "Mediterránea",
  "Francesa",
  "Americana",
  "Mariscos",
  "Parrilla",
  "Vegana",
];
