name: Deploy Sanity Studio

on:
  push:
    # Trigger on any branch except main
    branches-ignore:
      - main
    # Only trigger if files in the Sanity folder have changed
    paths:
      - "apps/mejores-restaurantes-sanity/**"

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
      SANITY_STUDIO_API_DATASET: ${{ vars.SANITY_STUDIO_API_DATASET }}
      SANITY_STUDIO_HOST: ${{ vars.SANITY_STUDIO_HOST }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16.x"

      - name: Check for changes in Sanity Studio
        id: sanity-changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            sanity:
              - 'apps/mejores-restaurantes-sanity/**'

      - name: Cache Node Modules
        if: steps.sanity-changes.outputs.sanity == 'true'
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Cache Turbo Build Cache
        if: steps.sanity-changes.outputs.sanity == 'true'
        uses: actions/cache@v3
        with:
          path: .turbo
          key: turbo-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        if: steps.sanity-changes.outputs.sanity == 'true'
        run: yarn install

      - name: Build Sanity Studio with Turbo
        if: steps.sanity-changes.outputs.sanity == 'true'
        run: yarn turbo run build --filter=apps/mejores-restaurantes-sanity...

      - name: Deploy Sanity Studio
        if: steps.sanity-changes.outputs.sanity == 'true'
        working-directory: apps/mejores-restaurantes-sanity
        run: yarn deploy

      - name: Skip Deploy
        if: steps.sanity-changes.outputs.sanity != 'true'
        run: echo "No changes detected in Sanity Studio. Skipping deployment."
