name: Deploy Development

on:
  push:
    # Trigger on any branch except main
    branches-ignore:
      - main
    # Only trigger if files in the Sanity folder have changed
    paths:
      - "apps/mejores-restaurantes-sanity/**"

jobs:
  deploy-sanity:
    runs-on: ubuntu-latest
    environment: Preview
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: apps/mejores-restaurantes-sanity
        run: yarn install

      - name: Deploy Sanity Studio (Dev)
        working-directory: apps/mejores-restaurantes-sanity
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
          SANITY_STUDIO_API_DATASET: ${{ vars.SANITY_STUDIO_API_DATASET }}
          SANITY_STUDIO_HOST: ${{ vars.SANITY_STUDIO_HOST }}
        run: yarn deploy
