name: Deploy sanity studio 

on: 
  push: 
    branches: [main] 


jobs: 
  deploy: 
    name: Build and deploy 
    runs-on: ubuntu-latest 
    env: SANITY_AUTH_TOKEN: ${{ secrets.SANITY_DEPLOY_TOKEN }} 
    steps: 
      - uses: actions/checkout@v2 
        with: 
          fetch-depth: 2 
      - uses: actions/setup-node@v2 
        with: 
          node-version: "16.x" 
      - name: Restore cached Node Modules 💾 
        id: cache-node-modules 
        uses: actions/cache@v3 
          with: 
            path: node_modules 
            key: node-modules-${{ hashFiles('package-lock.json') }} 
      - name: Install dependencies 
        run: npm install 
      - name: Deploy Studio 
        run: npm run deploy